name: Daily Leaderboard Update

on:
  schedule:
    # Run daily at 4:05 PM ET - 5 minutes after market close to allow snapshots to complete
    # Converted to UTC: 8:05 PM UTC (20:05) EST / 9:05 PM UTC (21:05) EDT
    - cron: '5 20 * * 1-5'   # EST (Standard Time)
    - cron: '5 21 * * 1-5'   # EDT (Daylight Saving Time)
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  update-priority-leaderboards:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Homepage Priority (5D) + Short-term Leaderboards
      run: |
        curl -X POST "https://apestogether.ai/api/cron/update-leaderboard-chunk?periods=1D,5D" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json"

  update-medium-leaderboards:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Medium-term Leaderboards
      run: |
        curl -X POST "https://apestogether.ai/api/cron/update-leaderboard-chunk?periods=1M,3M,YTD" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json"

  update-long-leaderboards:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Long-term Leaderboards
      run: |
        curl -X POST "https://apestogether.ai/api/cron/update-leaderboard-chunk?periods=1Y,5Y,MAX" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json"
