name: Collect Intraday Data (DISABLED - Using Vercel Cron)
on:
  # DISABLED: Duplicate of Vercel cron causing 2x collections
  # schedule:
  #   # Every 30 minutes during market hours (9:30 AM - 4:00 PM ET)
  #   # Converted to UTC: 1:30 PM - 8:00 PM UTC (13:30 - 20:00)
  #   - cron: '0,30 13-19 * * 1-5'
  #   - cron: '0 20 * * 1-5'  # Final 4:00 PM ET collection
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  collect-intraday-data:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Intraday Portfolio Data
        run: |
          response=$(curl -s -w "%{http_code}" -X POST \
            "https://apestogether.ai/api/cron/collect-intraday-data" \
            -H "Authorization: Bearer ${{ secrets.INTRADAY_CRON_TOKEN }}" \
            -H "Content-Type: application/json")
          
          http_code="${response: -3}"
          body="${response%???}"
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Error: Intraday data collection failed with status $http_code"
            exit 1
          fi
          
          echo "Intraday data collection completed successfully"
